defmodule AdventOfCode2025.Day07 do
  @moduledoc """
  --- Day 7: Laboratories ---
  You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

  Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

  Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

  Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

  You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

  For example:

  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

  .......S.......
  .......|.......
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  At that point, the original beam stops, and two new beams are emitted from the splitter:

  .......S.......
  .......|.......
  ......|^|......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  Those beams continue downward until they reach more splitters:

  .......S.......
  .......|.......
  ......|^|......
  ......|.|......
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

  .......S.......
  .......|.......
  ......|^|......
  ......|.|......
  .....|^|^|.....
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  This process continues until all of the tachyon beams reach a splitter or exit the manifold:

  .......S.......
  .......|.......
  ......|^|......
  ......|.|......
  .....|^|^|.....
  .....|.|.|.....
  ....|^|^|^|....
  ....|.|.|.|....
  ...|^|^|||^|...
  ...|.|.|||.|...
  ..|^|^|||^|^|..
  ..|.|.|||.|.|..
  .|^|||^||.||^|.
  .|.|||.||.||.|.
  |^|^|^|^|^|||^|
  |.|.|.|.|.|||.|
  To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

  Analyze your manifold diagram. How many times will the beam be split?

  --- Part Two ---
  With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

  With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

  Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

  To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

  In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

  .......S.......
  .......|.......
  ......|^.......
  ......|........
  .....|^.^......
  .....|.........
  ....|^.^.^.....
  ....|..........
  ...|^.^...^....
  ...|...........
  ..|^.^...^.^...
  ..|............
  .|^...^.....^..
  .|.............
  |^.^.^.^.^...^.
  |..............
  Or, there's the timeline where the particle alternated going left and right at each splitter:

  .......S.......
  .......|.......
  ......|^.......
  ......|........
  ......^|^......
  .......|.......
  .....^|^.^.....
  ......|........
  ....^.^|..^....
  .......|.......
  ...^.^.|.^.^...
  .......|.......
  ..^...^|....^..
  .......|.......
  .^.^.^|^.^...^.
  ......|........
  Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

  .......S.......
  .......|.......
  ......|^.......
  ......|........
  .....|^.^......
  .....|.........
  ....|^.^.^.....
  ....|..........
  ....^|^...^....
  .....|.........
  ...^.^|..^.^...
  ......|........
  ..^..|^.....^..
  .....|.........
  .^.^.^|^.^...^.
  ......|........
  In this example, in total, the particle ends up on 40 different timelines.

  Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?
  """

  @doc """
  Solves part 1 of the day 7 puzzle.
  """
  def part1(input) do
    input
    |> parse_input()
    |> solve_part1()
  end

  @doc """
  Solves part 2 of the day 7 puzzle.
  """
  def part2(input) do
    input
    |> parse_input()
    |> solve_part2()
  end

  @doc """
  Parses the input string into a data structure.
  """
  def parse_input(input) do
    lines = input
    |> String.trim()
    |> String.split("\n")

    # Create a map of the grid and find start position
    {grid, start_pos} = lines
    |> Enum.with_index()
    |> Enum.reduce({%{}, nil}, fn {line, row}, {grid_acc, start_acc} ->
      {line_grid, new_start} = line
      |> String.graphemes()
      |> Enum.with_index()
      |> Enum.reduce({%{}, start_acc}, fn {char, col}, {line_acc, start_pos} ->
        new_line_acc = Map.put(line_acc, {row, col}, char)
        new_start_pos = if char == "S", do: {row, col}, else: start_pos
        {new_line_acc, new_start_pos}
      end)

      {Map.merge(grid_acc, line_grid), new_start}
    end)

    {grid, start_pos, length(lines), String.length(List.first(lines))}
  end

  defp solve_part1({grid, start_pos, height, width}) do
    # Simulate tachyon beam splitting
    simulate_beams(grid, start_pos, height, width)
  end

  # Simulate beams and count splits
  defp simulate_beams(grid, start_pos, height, width) do
    # Start with one beam going down from S
    initial_beams = [{start_pos, :down}]

    # Track activated splitters and process beams
    process_beams(grid, initial_beams, MapSet.new(), height, width, 0)
  end

  # Process beams recursively until all exit or are absorbed
  defp process_beams(_grid, [], _activated_splitters, _height, _width, split_count) do
    split_count
  end

  defp process_beams(grid, beams, activated_splitters, height, width, split_count) do
    {new_beams, new_activated, new_splits} =
      Enum.reduce(beams, {[], activated_splitters, split_count},
        fn beam, {beam_acc, activated_acc, splits_acc} ->
          case advance_beam(grid, beam, height, width) do
            {:continue, next_beam} ->
              {[next_beam | beam_acc], activated_acc, splits_acc}

            {:hit_splitter, splitter_pos} ->
              # Check if this splitter has been activated before
              if MapSet.member?(activated_acc, splitter_pos) do
                # Already activated, beam is absorbed
                {beam_acc, activated_acc, splits_acc}
              else
                # First time hitting this splitter - activate it and create new beams
                new_activated_acc = MapSet.put(activated_acc, splitter_pos)
                # Create left and right beams from the splitter, both moving DOWN
                {splitter_row, splitter_col} = splitter_pos
                left_beam = {{splitter_row, splitter_col - 1}, :down}
                right_beam = {{splitter_row, splitter_col + 1}, :down}
                {[left_beam, right_beam | beam_acc], new_activated_acc, splits_acc + 1}
              end

            :exit ->
              # Beam exited the grid
              {beam_acc, activated_acc, splits_acc}
          end
        end)

    # Continue processing remaining beams
    process_beams(grid, new_beams, new_activated, height, width, new_splits)
  end

  # Advance a single beam one step
  defp advance_beam(grid, {{row, col}, direction}, height, width) do
    # Calculate next position based on direction
    {next_row, next_col} = case direction do
      :down -> {row + 1, col}
      :left -> {row, col - 1}
      :right -> {row, col + 1}
    end

    # Check if beam exits the grid
    cond do
      next_row >= height or next_row < 0 or next_col < 0 or next_col >= width ->
        :exit

      true ->
        # Check what's at the next position
        case Map.get(grid, {next_row, next_col}) do
          "^" ->
            # Hit a splitter
            {:hit_splitter, {next_row, next_col}}

          _ ->
            # Continue in same direction (empty space)
            {:continue, {{next_row, next_col}, direction}}
        end
    end
  end

  defp solve_part2({grid, start_pos, height, width}) do
    # Use memoization to avoid recalculating timelines for the same position
    memo = :ets.new(:timeline_memo, [:set, :private])
    initial_particle = {start_pos, :down}
    result = count_timelines_memoized(grid, initial_particle, height, width, memo)
    :ets.delete(memo)
    result
  end

  # Count timelines with memoization to avoid exponential complexity
  defp count_timelines_memoized(grid, particle, height, width, memo) do
    # Check if we've already calculated timelines for this particle state
    case :ets.lookup(memo, particle) do
      [{^particle, count}] ->
        count
      [] ->
        # Calculate and memoize the result
        count = calculate_timelines(grid, particle, height, width, memo)
        :ets.insert(memo, {particle, count})
        count
    end
  end

  defp calculate_timelines(grid, particle, height, width, memo) do
    case advance_beam(grid, particle, height, width) do
      {:continue, next_particle} ->
        # Continue with this single particle
        count_timelines_memoized(grid, next_particle, height, width, memo)

      {:hit_splitter, splitter_pos} ->
        # Quantum split: create two timelines
        {splitter_row, splitter_col} = splitter_pos
        left_particle = {{splitter_row, splitter_col - 1}, :down}
        right_particle = {{splitter_row, splitter_col + 1}, :down}

        # Each timeline contributes independently
        left_timelines = count_timelines_memoized(grid, left_particle, height, width, memo)
        right_timelines = count_timelines_memoized(grid, right_particle, height, width, memo)
        left_timelines + right_timelines

      :exit ->
        # Particle exited, this timeline is complete
        1
    end
  end

  @doc """
  Reads the input file for day 7.
  """
  def read_input do
    case File.read("inputs/day07.txt") do
      {:ok, content} -> content
      {:error, _} ->
        raise "Could not read input file for Day 7"
    end
  end
end
